name: comphys
dependencies:
- basemap=1.0.7=np110py35_0
- cycler=0.9.0=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- geos=3.3.3=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np110py35_0
- mkl=11.3.1=0
- numpy=1.10.4=py35_0
- openssl=1.0.2f=0
- pandas=0.17.1=np110py35_0
- pip=8.0.2=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py35_1
- seaborn=0.7.0=py35_0
- setuptools=19.6.2=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0

